#	top level Makefile for cyborg_autonomous software

all:
	cd cv_db ; make all
	cd servers ; make all
	cd test ; make all

clean:
	cd cv_db ; make clean
	cd servers ; make clean
	cd test ; make clean

doc:
	cd doc ; make all


cleandoc:
	cd doc ; make clean
