#	top level Makefile for cyborg_autonomous software

all:
	cd lib ; make all
	cd db ; make all
	cd servers ; make all
	cd test ; make all

clean:
	cd lib ; make clean
	cd db ; make clean
	cd servers ; make clean
	cd test ; make clean

doc:
	cd doc ; make all


cleandoc:
	cd doc ; make clean
