#	top level Makefile for cyborg_autonomous servers

all:
	cd 9dof_razor_imu ; make all
	cd gen_sss ; make all
	cd status ; make all

clean:
	cd 9dof_razor_imu ; make clean
	cd gen_sss ; make clean
	cd status ; make clean
